.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH filessh 1  "filessh"
.SH NAME
filessh \- Defines the command\-line interface for the application, specifying all possible arguments and options
.SH SYNOPSIS
\fBfilessh\fR [\fB\-p\fR|\fB\-\-port\fR] [\fB\-u\fR|\fB\-\-username\fR] <\fB\-k\fR|\fB\-\-private\-key\fR> [\fB\-o\fR|\fB\-\-openssh\-certificate\fR] [\fB\-\-install\-man\-pages\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIHOST\fR> <\fIPATH\fR>
.SH DESCRIPTION
Defines the command\-line interface for the application, specifying all possible arguments and options
.SH OPTIONS
.TP
\fB\-p\fR, \fB\-\-port\fR \fI<PORT>\fR [default: 22]
The port number to use for the SSH connection
.TP
\fB\-u\fR, \fB\-\-username\fR \fI<USERNAME>\fR
The username for logging into the remote host. If not provided, the SSH client may use the current local username or a default specified in SSH configuration
.TP
\fB\-k\fR, \fB\-\-private\-key\fR \fI<PRIVATE_KEY>\fR
The path to the private key file for public key authentication
.TP
\fB\-o\fR, \fB\-\-openssh\-certificate\fR \fI<OPENSSH_CERTIFICATE>\fR
An optional path to an OpenSSH certificate file for authentication
.TP
\fB\-\-install\-man\-pages\fR
Install the man pages for the application
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIHOST\fR>
The remote host to connect to (e.g., \*(Aqexample.com\*(Aq or \*(Aq192.168.1.100\*(Aq)
.TP
<\fIPATH\fR>
The initial directory path to open on the remote host after connecting
